title: Another Create Wiki
description: Another Create wiki, because people are getting tired of the Fandom Create wiki.
theme: just-the-docs
color_scheme: create

url: https://just-the-docs.github.io

permalink: pretty

aux_links:
  Get Create on CurseForge: https://www.curseforge.com/minecraft/mc-mods/create

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

callouts_level: quiet # or loud
callouts:
  highlight: 
    color: call-yellow
  important:
    title: Important
    color: call-blue
  new:
    title: New
    color: call-green
  note:
    title: Note
    color: call-purple
  warning:
    title: Warning
    color: call-red

# For copy button on code
enable_copy_code_button: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Project-Vyre/another-create-wiki" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
