title: Another Create Wiki
description: Another Create wiki, because people are getting tired of the Fandom Create wiki.
theme: dark

url: https://just-the-docs.github.io

aux_links:
  Get Create on CurseForge: https://www.curseforge.com/minecraft/mc-mods/create
